// import './class/lesson1'
// import './class/lesson2'
// import './class/lesson3'
// import './class/lesson4'
import 'babel-polyfill'
// import './class/lesson6'
// import './class/lesson8'
// import './class/lesson9'
// import './class/lesson10'
import './class/lesson11'